.headers on
.mode column

PRAGMA foreign_keys=ON;

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("ARS","ARSENAL","LONDON","PRESI_4","OWNER_4",6);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("BOU","BOURNEMOUTH","NO IDEA","PRESI_15","OWNER_15",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("BRI","BRIGHTON","NO IDEA","PRESI_18","OWNER_18",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("BUR","BURNLEY","MANCHESTER","PRESI_17","OWNER_17",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("CHE","CHELSEA","LONDON","PRESI_5","OWNER_5",4);


insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("CRY","CRYSTAL PALACE","LONDON","PRESI_16","OWNER_16",0);

-- insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
-- 	values("CAR","CARDIFF CITY","CARDIFF","PRESI_14","OWNER_14",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("EVE","EVERTON","Liverpool","PRESI_7","OWNER_7",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("HUD","HUDDERSFIED TOWN","HUDDERSFIED","PRESI_20","OWNER_20",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("LEI","LEICHESTER CITY","LEICHESTER","PRESI_8","OWNER_8",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("LIV","Liverpool FC","Liverpool","PRESI_1","OWNER_1",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("MC","MANCHESTER CITY","MANCHESTER","PRESI_2","OWNER_2",3);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("MUN","MANCHESTER UNITED","MANCHESTER","PRESI_3","OWNER_3",13);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("NEW","NEWCASTLE UNITED","NEWCASTLE","PRESI_12","OWNER_12",0);


insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("SOU","SOUTHHAMPTON FC","SOUTHHAMPTON","PRESI_13","OWNER_13",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("STK","STOKE CITY","STOKE","PRESI_10","OWNER_10",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("SWN","SWANSEA CITY","SWANSEA","PRESI_14","OWNER_14",0);



insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("TOT","TOTTENHAM HOTSPUR","LONDON","PRESI_6","OWNER_6",0);


insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("WAT","WATFORD FC","NO IDEA","PRESI_9","OWNER_9",0);

-- insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
-- 	values("WOL","WOLVERHAMTON WOLVES","NO IDEA","PRESI_10","OWNER_10",0);

insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("WBA","WEST BROMWICH","NO IDEA","PRESI_19","OWNER_19",0);


insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
	values("WHU","WEST HAM UNITED","LONDON","PRESI_11","OWNER_11",0);

-- insert into club(ABBR,CLUB_NAME,CLUB_CITY,PRESIDENT,OWNER,TITLES)
-- 	values("FUL","FULHAM","LONDON","PRESI_19","OWNER_19",0);




insert into SEASON(SEASON_ID)
	values(1);

