insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(1,1,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(2,2,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(3,3,1);

