CREATE TABLE CLUB(
	CLUB_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ABBR VARCHAR(5) UNIQUE NOT NULL,
	CLUB_NAME VARCHAR(30) NOT NULL UNIQUE,
	CLUB_CITY VARCHAR(30) NOT NULL,
	PRESIDENT VARCHAR(30),
	OWNER VARCHAR(30) NOT NULL,
	MANAGER VARCHAR(30) NOT NULL UNIQUE,
	ASST_MANAGER VARCHAR(30) UNIQUE,
	LAST_RELEGATED INTEGER,
	TITLES INTEGER
);

CREATE TABLE PLAYER(
	PID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR(30) NOT NULL,
	CLUB_ID INTEGER,
	CONTRACT_TILL DATE,
	NATIONALITY VARCHAR(30),
	SALARY INTEGER,
	PREF_POSITION VARCHAR(30) NOT NULL,
	JERSEY_NO INTEGER,
	BUYOUT_CLAUSE INTEGER,
	YELLOW_COUNT INTEGER DEFAULT 0 NOT NULL,
	RED_COUNT INTEGER DEFAULT 0 NOT NULL,
	SUPENSION_COUNT INTEGER DEFAULT 0 NOT NULL,
	FOREIGN KEY (CLUB_ID) REFERENCES CLUB
);

CREATE TABLE REFEREE(
	RID INTEGER PRIMARY KEY,
	REFEREE_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE MATCH(
	MATCH_ID INTEGER NOT NULL,
	MATCH_DATE DATE NOT NULL,
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	PRIMARY KEY (MATCH_ID,SEASON_ID),
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	HOME_CLUB_ID INTEGER NOT NULL,
	AWAY_CLUB_ID INTEGER NOT NULL,
	FOREIGN KEY (HOME_CLUB_ID) REFERENCES CLUB(CLUB_ID),
	FOREIGN KEY (AWAY_CLUB_ID) REFERENCES CLUB(CLUB_ID),
	CHECK (HOME_CLUB_ID!=AWAY_CLUB_ID),
	HOME_SCORE INTEGER DEFAULT 0 NOT NULL,
	AWAY_SCORE INTEGER DEFAULT 0 NOT NULL,
	AUDIENCE INTEGER DEFAULT 0 NOT NULL,
	MOTM INTEGER NOT NULL,
	FIRST_HALF_ST INTEGER DEFAULT 0 NOT NULL,
	SECOND_HALF_ST INTEGER DEFAULT 0 NOT NULL,
	MAIN_REFEREE INTEGER NOT NULL,
	ASST1 INTEGER NOT NULL,
	ASST2 INTEGER NOT NULL,
	FOURTH_OFFICIAL INTEGER NOT NULL,
	FOREIGN KEY (MAIN_REFEREE) REFERENCES REFEREE(RID),
	FOREIGN KEY (ASST1) REFERENCES REFEREE(RID),
	FOREIGN KEY (ASST2) REFERENCES REFEREE(RID),
	FOREIGN KEY (FOURTH_OFFICIAL) REFERENCES REFEREE(RID),
	WIN INTEGER DEFAULT 0 NOT NULL,
	FORMATION VARCHAR(10) NOT NULL,
	FORMATION VARCHAR(10) NOT NULL
);

CREATE TABLE GOALS(
	GOAL_ID INTEGER PRIMARY KEY,
	MATCH_ID INTEGER NOT NULL,
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	FOREIGN KEY (MATCH_ID,SEASON_ID) REFERENCES MATCH(MATCH_ID,SEASON_ID),
	PID INTEGER NOT NULL,
	FOREIGN KEY (PID) REFERENCES PLAYER(PID),
	GOAL_TIME INTEGER NOT NULL,
	EXTRATIME INTEGER,
	ASSIST_BY INTEGER,
	FOREIGN KEY (ASSIST_BY) REFERENCES PLAYER(PID),
	SCORING_CLUB INTEGER NOT NULL,
	OWN_GOAL BOOLEAN
);

CREATE TABLE BOOKING(
	BOOKING_ID INTEGER PRIMARY KEY,
	MATCH_ID INTEGER NOT NULL,
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	FOREIGN KEY (MATCH_ID,SEASON_ID) REFERENCES MATCH(MATCH_ID,SEASON_ID),
	PID INTEGER NOT NULL,
	FOREIGN KEY (PID) REFERENCES PLAYER(PID),
	BOOKING_TYPE CHAR(1) NOT NULL,
	CLUB_ID INTEGER NOT NULL,
	FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
	CHECK (BOOKING_TYPE IN ("Y","R"))
);

CREATE TABLE CLUB_IN_SEASON(
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	CLUB_ID INTEGER NOT NULL,
	FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
	PRIMARY KEY (CLUB_ID,SEASON_ID),
	WON INTEGER DEFAULT 0 NOT NULL,
	LOSE INTEGER DEFAULT 0 NOT NULL,
	DRAW  INTEGER DEFAULT 0 NOT NULL,
	GOAL_FOR INTEGER DEFAULT 0 NOT NULL,
	GOAL_AGAINST INTEGER DEFAULT 0 NOT NULL,
	GOAL_DIFF INTEGER DEFAULT 0 NOT NULL,
	PLAYED INTEGER DEFAULT 0 NOT NULL,
	POINTS INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE LINEUP(
	CLUB_ID INTEGER NOT NULL,
	FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
	MATCH_ID INTEGER NOT NULL,
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	FOREIGN KEY (MATCH_ID,SEASON_ID) REFERENCES MATCH(MATCH_ID,SEASON_ID),
	PID INTEGER NOT NULL,
	FOREIGN KEY (PID) REFERENCES PLAYER(PID),
	isSUB BOOLEAN DEFAULT 0,
	POSITION VARCHAR(30) NOT NULL,
	PRIMARY KEY (CLUB_ID,MATCH_ID,SEASON_ID,PID)
);

CREATE TABLE SUBSTITUTION(
	SUBSTITUTION_COUNT INTEGER DEFAULT 0 NOT NULL,
	MATCH_ID INTEGER NOT NULL,
	CLUB_ID INTEGER NOT NULL,
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	FOREIGN KEY (MATCH_ID,SEASON_ID) REFERENCES MATCH(MATCH_ID,SEASON_ID),
	FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
	PLAYER_IN_ID INTEGER NOT NULL,
	PLAYER_OUT_ID INTEGER NOT NULL,
	FOREIGN KEY (PLAYER_IN_ID) REFERENCES PLAYER(PID),
	FOREIGN KEY (PLAYER_OUT_ID) REFERENCES PLAYER(PID),
	TIME INTEGER NOT NULL,
	PHASE INTEGER NOT NULL,
	CHECK (PHASE >=0 AND PHASE <=3),  
	PRIMARY KEY (SEASON_ID, MATCH_ID, CLUB_ID, SUBSTITUTION_COUNT)
);

CREATE TABLE STATS(
	PID INTEGER NOT NULL,
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (PID) REFERENCES PLAYER(PID),
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	PRIMARY KEY (PID, SEASON_ID),
	GOALS_SCORED INTEGER DEFAULT 0 NOT NULL,
	ASSISTS INTEGER DEFAULT 0 NOT NULL,
	CLEAN_SHEET INTEGER DEFAULT 0 NOT NULL,
	YELLOW_COUNT INTEGER DEFAULT 0 NOT NULL,
	RED_COUNT INTEGER DEFAULT 0 NOT NULL,
	MATCHES_PLAYED INTEGER DEFAULT 0 NOT NULL,
);

CREATE TABLE SEASON(
	SEASON_ID INTEGER PRIMARY KEY,
	SEASON_YEAR INTEGER NOT NULL,
	WINNER INTEGER NOT NULL,
	FOREIGN KEY (WINNER) REFERENCES CLUB(CLUB_ID),
	TOP_SCORER INTEGER NOT NULL,
	FOREIGN KEY(TOP_SCORER) REFERENCES PLAYER(PID),
	TOP_ASSISTS INTEGER NOT NULL,
	FOREIGN KEY(TOP_ASSISTS) REFERENCES PLAYER(PID),
	TOP_CLEAN_SHEETS INTEGER NOT NULL,
	FOREIGN KEY(TOP_CLEAN_SHEETS) REFERENCES PLAYER(PID),
	POTS INTEGER NOT NULL,
	FOREIGN KEY (POTS) REFERENCES PLAYER(PID),
	TOTAL_RED_CARDS INT DEFAULT 0 NOT NULL,
	TOTAL_YELLOW_CARDS INT DEFAULT 0 NOT NULL,
);

CREATE TABLE TRANSFER(
	PID INTEGER NOT NULL,
	FOREIGN KEY (PID) REFERENCES PLAYER(PID),
	SEASON_ID INTEGER NOT NULL,
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(SEASON_ID),
	PRIMARY KEY (PID, SEASON_ID),
	ARRIVING_CLUB INTEGER NOT NULL,
	DEPARTING_CLUB INTEGER,
	FOREIGN KEY (ARRIVING_CLUB) REFERENCES CLUB(CLUB_ID),
	FOREIGN KEY (DEPARTING_CLUB) REFERENCES CLUB(CLUB_ID),
	TRANSFER_AMOUNT INTEGER,
	TRANSFER_TYPE CHAR(1) NOT NULL,
	CHECK (TRANSFER_TYPE IN ("L", "B")),
	TRANSFER_DATE DATE NOT NULL,
);