insert into MATCH_REFEREE(MATCH_ID,MAIN_REFEREE,ASST1,ASST2,FOURTH_OFFICIAL) values(1,1,2,3,4);
insert into MATCH_REFEREE(MATCH_ID,MAIN_REFEREE,ASST1,ASST2,FOURTH_OFFICIAL) values(2,5,3,6,4);
insert into MATCH_REFEREE(MATCH_ID,MAIN_REFEREE,ASST1,ASST2,FOURTH_OFFICIAL) values(3,3,2,4,5);
insert into MATCH_REFEREE(MATCH_ID,MAIN_REFEREE,ASST1,ASST2,FOURTH_OFFICIAL) values(4,1,2,3,4);
insert into MATCH_REFEREE(MATCH_ID,MAIN_REFEREE,ASST1,ASST2,FOURTH_OFFICIAL) values(5,7,3,6,4);

