insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(1,1,1);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(2,1,2);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(3,1,3);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(4,1,4);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(5,1,5);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(6,1,6);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(7,1,7);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(8,1,8);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(9,1,9);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(10,1,10);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(11,1,11);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(12,1,12);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(13,1,13);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(14,1,14);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(15,1,15);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(16,1,16);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(17,1,17);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(18,1,18);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(19,1,19);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(20,1,20);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(21,1,21);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(22,1,22);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(23,1,23);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(24,1,24);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(25,1,25);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(26,1,26);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(27,1,27);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(28,1,28);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(29,1,29);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(30,1,30);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(31,1,31);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(32,1,32);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(33,1,33);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(34,1,34);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(35,1,35);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(36,1,36);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(37,1,37);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(38,1,38);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(39,1,39);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(40,1,40);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(41,1,41);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(42,1,42);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(43,1,43);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(44,1,44);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(45,1,45);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(46,1,46);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(47,1,47);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(48,1,48);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(49,1,49);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(50,1,50);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(51,1,51);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(52,1,52);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(53,1,53);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(54,1,54);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(55,1,55);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(56,1,56);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(57,1,57);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(58,1,58);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(59,1,59);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(60,1,60);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(61,1,61);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(62,1,62);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(63,1,63);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(64,1,64);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(65,1,65);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(66,1,66);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(67,1,67);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(68,1,68);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(69,1,69);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(70,1,70);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(71,1,71);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(72,1,72);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(73,1,73);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(74,1,74);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(75,1,75);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(76,1,76);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(77,1,77);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(78,1,78);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(79,1,79);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(80,1,80);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(81,1,81);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(82,1,82);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(83,1,83);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(84,1,84);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(85,1,85);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(86,1,86);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(87,1,87);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(88,1,88);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(89,1,89);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(90,1,90);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(91,1,91);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(92,1,92);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(93,1,93);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(94,1,94);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(95,1,95);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(96,1,96);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(97,1,97);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(98,1,98);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(99,1,99);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(100,1,100);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(101,1,101);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(102,1,102);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(103,1,103);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(104,1,104);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(105,1,105);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(106,1,106);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(107,1,107);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(108,1,108);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(109,1,109);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(110,1,110);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(111,1,111);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(112,1,112);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(113,1,113);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(114,1,114);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(115,1,115);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(116,1,116);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(117,1,117);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(118,1,118);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(119,1,119);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(120,1,120);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(121,1,121);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(122,1,122);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(123,1,123);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(124,1,124);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(125,1,125);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(126,1,126);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(127,1,127);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(128,1,128);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(129,1,129);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(130,1,130);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(131,1,131);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(132,1,132);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(133,1,133);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(134,1,134);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(135,1,135);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(136,1,136);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(137,1,137);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(138,1,138);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(139,1,139);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(140,1,140);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(141,1,141);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(142,1,142);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(143,1,143);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(144,1,144);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(145,1,145);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(146,1,146);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(147,1,147);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(148,1,148);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(149,1,149);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(150,1,150);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(151,1,151);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(152,1,152);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(153,1,153);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(154,1,154);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(155,1,155);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(156,1,156);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(157,1,157);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(158,1,158);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(159,1,159);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(160,1,160);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(161,1,161);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(162,1,162);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(163,1,163);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(164,1,164);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(165,1,165);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(166,1,166);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(167,1,167);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(168,1,168);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(169,1,169);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(170,1,170);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(171,1,171);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(172,1,172);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(173,1,173);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(174,1,174);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(175,1,175);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(176,1,176);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(177,1,177);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(178,1,178);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(179,1,179);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(180,1,180);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(181,1,181);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(182,1,182);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(183,1,183);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(184,1,184);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(185,1,185);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(186,1,186);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(187,1,187);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(188,1,188);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(189,1,189);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(190,1,190);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(191,1,191);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(192,1,192);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(193,1,193);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(194,1,194);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(195,1,195);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(196,1,196);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(197,1,197);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(198,1,198);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(199,1,199);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(200,1,200);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(201,1,201);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(202,1,202);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(203,1,203);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(204,1,204);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(205,1,205);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(206,1,206);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(207,1,207);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(208,1,208);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(209,1,209);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(210,1,210);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(211,1,211);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(212,1,212);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(213,1,213);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(214,1,214);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(215,1,215);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(216,1,216);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(217,1,217);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(218,1,218);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(219,1,219);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(220,1,220);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(221,1,221);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(222,1,222);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(223,1,223);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(224,1,224);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(225,1,225);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(226,1,226);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(227,1,227);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(228,1,228);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(229,1,229);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(230,1,230);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(231,1,231);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(232,1,232);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(233,1,233);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(234,1,234);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(235,1,235);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(236,1,236);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(237,1,237);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(238,1,238);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(239,1,239);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(240,1,240);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(241,1,241);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(242,1,242);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(243,1,243);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(244,1,244);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(245,1,245);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(246,1,246);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(247,1,247);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(248,1,248);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(249,1,249);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(250,1,250);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(251,1,251);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(252,1,252);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(253,1,253);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(254,1,254);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(255,1,255);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(256,1,256);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(257,1,257);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(258,1,258);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(259,1,259);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(260,1,260);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(261,1,261);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(262,1,262);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(263,1,263);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(264,1,264);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(265,1,265);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(266,1,266);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(267,1,267);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(268,1,268);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(269,1,269);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(270,1,270);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(271,1,271);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(272,1,272);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(273,1,273);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(274,1,274);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(275,1,275);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(276,1,276);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(277,1,277);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(278,1,278);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(279,1,279);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(280,1,280);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(281,1,281);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(282,1,282);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(283,1,283);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(284,1,284);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(285,1,285);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(286,1,286);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(287,1,287);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(288,1,288);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(289,1,289);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(290,1,290);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(291,1,291);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(292,1,292);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(293,1,293);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(294,1,294);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(295,1,295);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(296,1,296);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(297,1,297);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(298,1,298);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(299,1,299);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(300,1,300);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(301,1,301);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(302,1,302);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(303,1,303);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(304,1,304);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(305,1,305);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(306,1,306);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(307,1,307);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(308,1,308);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(309,1,309);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(310,1,310);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(311,1,311);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(312,1,312);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(313,1,313);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(314,1,314);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(315,1,315);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(316,1,316);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(317,1,317);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(318,1,318);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(319,1,319);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(320,1,320);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(321,1,321);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(322,1,322);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(323,1,323);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(324,1,324);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(325,1,325);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(326,1,326);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(327,1,327);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(328,1,328);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(329,1,329);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(330,1,330);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(331,1,331);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(332,1,332);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(333,1,333);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(334,1,334);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(335,1,335);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(336,1,336);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(337,1,337);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(338,1,338);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(339,1,339);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(340,1,340);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(341,1,341);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(342,1,342);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(343,1,343);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(344,1,344);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(345,1,345);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(346,1,346);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(347,1,347);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(348,1,348);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(349,1,349);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(350,1,350);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(351,1,351);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(352,1,352);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(353,1,353);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(354,1,354);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(355,1,355);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(356,1,356);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(357,1,357);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(358,1,358);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(359,1,359);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(360,1,360);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(361,1,361);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(362,1,362);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(363,1,363);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(364,1,364);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(365,1,365);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(366,1,366);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(367,1,367);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(368,1,368);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(369,1,369);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(370,1,370);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(371,1,371);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(372,1,372);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(373,1,373);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(374,1,374);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(375,1,375);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(376,1,376);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(377,1,377);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(378,1,378);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(379,1,379);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(380,1,380);
