insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(1,1,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(2,3,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(3,2,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(4,2,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(5,1,3);
