-- Non-trivial queries


-- How many minutes played by each player?

SELECT P.NAME,(
(SELECT COALESCE(SUM(90-S.STIME),0) FROM SUBSTITUTION AS S, LINEUP AS L
WHERE L.PLAYER_ID = P.PLAYER_ID AND S.PLAYER_IN=L.PLAYER_ID 
AND S.MATCH_ID=L.MATCH_ID AND isSUB = 0 AND SUB_PLAYED = 1
)+
(SELECT COALESCE(SUM(BOOKING_TIME),0) FROM (BOOKING NATURAL JOIN LINEUP)
WHERE PLAYER_ID = P.PLAYER_ID AND isSUB = 1 AND SUB_PLAYED = -1 AND BOOKING_TYPE='R'
)
+
(SELECT COALESCE(SUM(S.STIME),0) FROM SUBSTITUTION AS S, LINEUP AS L
WHERE L.PLAYER_ID = P.PLAYER_ID AND S.PLAYER_OUT=L.PLAYER_ID 
AND S.MATCH_ID=L.MATCH_ID AND isSUB = 1 AND SUB_PLAYED = -1
)+
(SELECT 90*COUNT(PLAYER_ID) FROM LINEUP
WHERE PLAYER_ID = P.PLAYER_ID AND SUB_PLAYED = 0 AND isSUB = 0
)) AS MINUTES
FROM PLAYER AS P
ORDER BY MINUTES DESC;


-- Match Timeline

SELECT MATCH_ID AS MATCH_ID,"GOAL" AS TYPE,GOAL_TIME AS TIME, A.NAME AS PLAYER, B.NAME AS ASSISTED_BY, NULL AS PLAYER_IN, NULL AS PLAYER_OUT, NULL AS CARD_TYPE,C.CLUB_NAME AS CLUB
FROM GOALS,PLAYER AS A,PLAYER AS B,CLUB AS C
WHERE MATCH_ID  = 1 AND A.PLAYER_ID = GOALS.PLAYER_ID AND B.PLAYER_ID = GOALS.ASSIST_BY AND  GOALS.CLUB_ID = C.CLUB_ID
UNION
SELECT MATCH_ID AS MATCH_ID,"SUBSTITUTION" AS TYPE,STIME AS TIME, NULL AS PLAYER, NULL AS ASSISTED_BY, A.NAME AS PLAYER_IN, B.NAME AS PLAYER_OUT, NULL AS CARD_TYPE,C.CLUB_NAME AS CLUB
FROM SUBSTITUTION,PLAYER AS A,PLAYER AS B,CLUB AS C
WHERE MATCH_ID  = 1 AND A.PLAYER_ID = SUBSTITUTION.PLAYER_IN AND B.PLAYER_ID = SUBSTITUTION.PLAYER_OUT AND SUBSTITUTION.CLUB_ID = C.CLUB_ID
UNION
SELECT MATCH_ID AS MATCH_ID,"BOOKING" AS TYPE,BOOKING_TIME AS TIME, A.NAME AS PLAYER, NULL AS ASSISTED_BY, NULL AS PLAYER_IN, NULL AS PLAYER_OUT, BOOKING_TYPE AS CARD_TYPE,C.CLUB_NAME AS CLUB
FROM BOOKING,PLAYER AS A,CLUB AS C
WHERE MATCH_ID  = 1 AND A.PLAYER_ID = BOOKING.PLAYER_ID AND  
C.CLUB_ID = ( SELECT CLUB_ID FROM CLUB_PLAYER AS D WHERE D.PLAYER_ID = A.PLAYER_ID)
ORDER BY TIME;


-- Find all defenders who scored own goal ( and all the data...)

WITH A(PLAYER_ID,MATCH_ID,CLUB_ID) AS
(SELECT DISTINCT G.PLAYER_ID, G.MATCH_ID, L.CLUB_ID 
	FROM GOALS AS G, LINEUP AS L
WHERE G.MATCH_ID = L.MATCH_ID AND G.PLAYER_ID = L.PLAYER_ID 
AND G.OWN_GOAL = 1 AND L.POSITION IN ('LB','CB','RB'))
SELECT NAME, CLUB_NAME, ((MATCH_ID-1)/6 + 1) AS SEASON, ((MATCH_ID-1)%6+1) AS MATCH_NO
FROM (PLAYER NATURAL JOIN (A NATURAL JOIN CLUB));


-- Past between 2 clubs

SELECT C1.CLUB_NAME AS HOME_TEAM, C2.CLUB_NAME AS AWAY_TEAM,HOME_SCORE AS HOME_SCORE,AWAY_SCORE AS AWAY_SCORE
FROM CLUB AS C1, CLUB AS C2,MATCH NATURAL JOIN (SELECT * FROM PLAYING_CLUBS WHERE HOME_CLUB=1 AND AWAY_CLUB = 2)
WHERE C1.CLUB_ID = 1 AND C2.CLUB_ID = 2
UNION 
SELECT C1.CLUB_NAME AS HOME_TEAM, C2.CLUB_NAME AS AWAY_TEAM2,HOME_SCORE AS HOME_SCORE,AWAY_SCORE AS AWAY_SCORE
FROM CLUB AS C1, CLUB AS C2,MATCH NATURAL JOIN (SELECT * FROM PLAYING_CLUBS WHERE HOME_CLUB=2 AND AWAY_CLUB = 1)
WHERE C1.CLUB_ID = 2 AND C2.CLUB_ID = 1;


-- No of goals by sub

SELECT B.PLAYER_ID, COUNT (*) AS GOALS_SCORED
FROM MATCH AS A, GOALS AS B, LINEUP AS C
WHERE A.MATCH_ID = B.MATCH_ID AND B.MATCH_ID = C.MATCH_ID AND B.PLAYER_ID = C.PLAYER_ID AND C.SUB_PLAYED = 1
GROUP BY B.PLAYER_ID;