-- Non-trivial queries


-- Find all defenders who scored own goal ( and all the data...)

WITH A(PLAYER_ID,MATCH_ID,CLUB_ID) AS
(SELECT DISTINCT G.PLAYER_ID, G.MATCH_ID, L.CLUB_ID 
	FROM GOALS AS G, LINEUP AS L
WHERE G.MATCH_ID = L.MATCH_ID AND G.PLAYER_ID = L.PLAYER_ID 
AND G.OWN_GOAL = 1 AND L.POSITION IN ('LB','CB','RB'))
SELECT NAME, CLUB_NAME, ((MATCH_ID-1)/6 + 1) AS SEASON, ((MATCH_ID-1)%6+1) AS MATCH_NO
FROM (PLAYER NATURAL JOIN (A NATURAL JOIN CLUB));


-- How many minutes played by each player?

LINEUP -> PLAYER_ID, MATCH_ID
BOOKING -> RED, BOOKING_TIME 
MATCH,PLAYER IN SUBSTITUTION
ELSE MATCH -> +90
PLAYER -> PLAYER_ID, NAME

SELECT 90*COUNT(PLAYER_ID) FROM LINEUP
WHERE PLAYER_ID = 1 AND SUB_PLAYED = 0 AND 
(PLAYER_ID, MATCH_ID) NOT IN 
(SELECT PLAYER_ID, MATCH_ID FROM BOOKING WHERE BOOKING_TYPE = 'R')