insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(1,1,1);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(2,1,2);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(3,1,3);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(4,1,4);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(5,1,5);
insert into MATCH_IN_SEASON(MATCH_ID,SEASON_ID,MATCH_COUNT)
values(6,1,6);
