insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(1,1,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(2,2,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(3,3,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(4,4,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(5,5,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(6,6,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(7,7,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(8,8,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(9,9,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(10,10,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(11,11,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(12,12,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(13,13,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(14,14,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(15,15,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(16,16,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(17,17,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(18,18,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(19,19,1);
insert into CLUB_MANAGER(MANAGER_ID,CLUB_ID,SEASON_ID)
	values(20,20,1);
