insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(1,1,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(2,18,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(3,5,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(4,6,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(5,7,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(6,14,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(7,19,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(8,3,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(9,13,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(10,12,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(11,16,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(12,2,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(13,4,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(14,9,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(15,10,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(16,14,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(17,15,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(18,8,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(19,17,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(20,11,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(21,2,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(22,6,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(23,8,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(24,13,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(25,18,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(26,12,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(27,5,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(28,19,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(29,10,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(30,17,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(31,11,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(32,1,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(33,3,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(34,7,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(35,9,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(36,14,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(37,15,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(38,4,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(39,16,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(40,20,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(41,2,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(42,6,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(43,8,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(44,10,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(45,13,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(46,18,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(47,19,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(48,17,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(49,5,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(50,12,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(51,20,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(52,4,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(53,7,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(54,11,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(55,14,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(56,15,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(57,16,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(58,9,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(59,3,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(60,1,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(61,8,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(62,2,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(63,12,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(64,15,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(65,19,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(66,20,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(67,5,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(68,1,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(69,7,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(70,13,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(71,10,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(72,4,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(73,6,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(74,11,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(75,16,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(76,17,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(77,18,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(78,3,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(79,14,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(80,9,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(81,20,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(82,5,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(83,8,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(84,11,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(85,13,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(86,15,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(87,16,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(88,14,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(89,7,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(90,17,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(91,12,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(92,1,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(93,6,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(94,10,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(95,18,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(96,19,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(97,2,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(98,3,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(99,9,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(100,4,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(101,15,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(102,8,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(103,13,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(104,14,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(105,16,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(106,20,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(107,17,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(108,11,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(109,5,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(110,7,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(111,1,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(112,2,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(113,4,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(114,6,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(115,9,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(116,10,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(117,19,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(118,12,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(119,18,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(120,3,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(121,20,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(122,6,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(123,12,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(124,13,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(125,16,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(126,17,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(127,10,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(128,14,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(129,4,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(130,8,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(131,3,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(132,9,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(133,18,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(134,19,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(135,1,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(136,2,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(137,5,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(138,7,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(139,11,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(140,15,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(141,5,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(142,3,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(143,7,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(144,9,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(145,15,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(146,18,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(147,19,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(148,1,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(149,2,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(150,11,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(151,20,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(152,4,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(153,6,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(154,8,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(155,16,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(156,17,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(157,13,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(158,14,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(159,10,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(160,12,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(161,4,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(162,8,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(163,6,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(164,16,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(165,13,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(166,14,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(167,20,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(168,12,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(169,10,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(170,17,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(171,9,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(172,1,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(173,3,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(174,5,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(175,18,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(176,15,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(177,11,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(178,19,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(179,2,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(180,7,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(181,1,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(182,7,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(183,3,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(184,11,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(185,14,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(186,15,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(187,16,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(188,20,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(189,4,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(190,9,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(191,17,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(192,2,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(193,5,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(194,8,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(195,12,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(196,18,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(197,19,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(198,10,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(199,13,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(200,6,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(201,2,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(202,5,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(203,8,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(204,10,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(205,13,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(206,18,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(207,12,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(208,6,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(209,19,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(210,3,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(211,4,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(212,9,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(213,15,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(214,7,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(215,14,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(216,16,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(217,20,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(218,11,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(219,1,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(220,17,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(221,5,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(222,6,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(223,8,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(224,13,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(225,18,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(226,19,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(227,17,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(228,2,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(229,10,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(230,12,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(231,3,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(232,1,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(233,4,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(234,7,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(235,9,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(236,15,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(237,20,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(238,11,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(239,14,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(240,16,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(241,16,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(242,20,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(243,8,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(244,5,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(245,7,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(246,13,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(247,14,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(248,11,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(249,15,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(250,17,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(251,4,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(252,2,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(253,3,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(254,9,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(255,12,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(256,19,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(257,1,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(258,6,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(259,10,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(260,18,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(261,17,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(262,7,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(263,15,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(264,16,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(265,20,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(266,11,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(267,8,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(268,13,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(269,14,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(270,5,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(271,9,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(272,2,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(273,3,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(274,4,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(275,10,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(276,19,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(277,18,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(278,6,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(279,12,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(280,1,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(281,4,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(282,9,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(283,14,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(284,16,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(285,17,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(286,18,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(287,10,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(288,3,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(289,11,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(290,6,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(291,12,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(292,7,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(293,8,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(294,13,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(295,19,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(296,20,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(297,5,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(298,1,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(299,2,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(300,15,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(301,2,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(302,8,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(303,15,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(304,10,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(305,6,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(306,3,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(307,12,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(308,13,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(309,20,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(310,18,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(311,19,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(312,7,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(313,1,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(314,5,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(315,7,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(316,2,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(317,3,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(318,9,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(319,15,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(320,18,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(321,19,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(322,11,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(323,1,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(324,5,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(325,14,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(326,4,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(327,6,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(328,8,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(329,16,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(330,10,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(331,17,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(332,13,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(333,12,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(334,20,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(335,3,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(336,2,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(337,4,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(338,9,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(339,19,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(340,18,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(341,1,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(342,15,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(343,11,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(344,7,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(345,10,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(346,4,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(347,6,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(348,8,7);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(349,13,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(350,14,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(351,16,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(352,20,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(353,12,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(354,17,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(355,3,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(356,15,6);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(357,2,16);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(358,9,20);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(359,18,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(360,19,17);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(361,7,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(362,11,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(363,1,4);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(364,5,10);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(365,16,14);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(366,9,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(367,5,8);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(368,11,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(369,17,13);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(370,20,12);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(371,4,2);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(372,6,19);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(373,8,1);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(374,10,3);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(375,12,18);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(376,13,5);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(377,14,11);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(378,16,15);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(379,17,9);
insert into PLAYING_CLUBS(MATCH_ID,HOME_CLUB,AWAY_CLUB)
	values(380,20,7);
